# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 600s
options:
  substitution_option: ALLOW_LOOSE
  machineType: E2_HIGHCPU_8
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/fastly-purge-token/versions/latest
      env: FASTLY_API_TOKEN
steps:
  - name: us-central1-docker.pkg.dev/k8s-staging-test-infra/images/kubekins-e2e:latest-master
    entrypoint: runner.sh
    env:
      - BUCKET_NAME=$_BUCKET_NAME
      - FASTLY_SERVICE_NAME=$_FASTLY_SERVICE_NAME
    secretEnv:
      - FASTLY_API_TOKEN
    args:
      - scripts/upload-to-gcs.sh
substitutions:
  _BUCKET_NAME: random-bucket
  _FASTLY_SERVICE_NAME: dl.k8s.dev
