name: build

on:
  push:
    branches:
      - 'master'
  pull_request:

permissions: {}

jobs:
  build:

    name: npm
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build-prod
